### ISSUE TITLE
Make output directory optional

### ISSUE THREAD

**Issue by swissspidy** [swissspidy/wp-cli-makepot#8]
If no output directory is passed, the command could write to `<slug>.pot` in the current directory by default.

**Comment by bradyvercher** [comment]
In the node package, I tried to make everything optional and use discoverable metadata in the project to set the defaults. In the case of the output directory, I use the `Domain Path` header if it exists before using the current directory as the default.

**Comment by swissspidy** [comment]
@bradyvercher Thanks! I almost forgot about that one.

In d4d845ecbed7153ba3e2f3a92cdac853eea01490:

* Use `destination` when provided. This needs to be a full path including file name.
* Use `<source>/<Domain Path>/<slug>.pot` when `Domain Path` is set.
* Use `./<slug>.pot` as last resort.
